# This is corax's configuration file. corax expects to find this configuration file
# based on the Python Click package's get_app_dir() method (see docs for your system
# https://click.palletsprojects.com/en/7.x/api/#click.get_app_dir). If the file
# does not exist in that location, corax will attempt to create it for you upon
# invokation of `corax config`.
# The corax configuration file is written in YAML. Please make sure to follow YAML
# syntax to ensure successful operation.
#
# Use this section to configure API keys.
VIRUSTOTAL: Replace with VirusTotal API key
ABUSEIP: Replace with AbuseIP DB API key
URLSCAN: Replace with URLScan.io API key
HIBP: Replace with HaveIBeenPwned API key
EMAILREP: Replace with EmailRep.io API key


#TODO: Add app wide configurations
#  - Set user-agent to use for web based requests